-- ============================================================
-- ECU ve Okuma Yöntemleri Seed Verisi
-- ============================================================

-- ----------------------------------------
-- ECU MODÜLLERI
-- ----------------------------------------
INSERT IGNORE INTO `ecus` (`name`, `brand`, `is_active`) VALUES

-- Bosch
('Bosch ME7.4.4',       'Bosch', 1),
('Bosch ME7.4.5',       'Bosch', 1),
('Bosch ME7.4.6',       'Bosch', 1),
('Bosch ME7.5',         'Bosch', 1),
('Bosch ME7.5.10',      'Bosch', 1),
('Bosch ME7.5.20',      'Bosch', 1),
('Bosch ME7.6.1',       'Bosch', 1),
('Bosch ME7.6.2',       'Bosch', 1),
('Bosch ME7.8.8',       'Bosch', 1),
('Bosch ME7.9',         'Bosch', 1),
('Bosch ME7.9.52',      'Bosch', 1),
('Bosch ME9.6',         'Bosch', 1),
('Bosch ME9.7',         'Bosch', 1),
('Bosch MED7',          'Bosch', 1),
('Bosch MED9.1',        'Bosch', 1),
('Bosch MED9.5',        'Bosch', 1),
('Bosch MED17',         'Bosch', 1),
('Bosch MED17.1',       'Bosch', 1),
('Bosch MED17.1.1',     'Bosch', 1),
('Bosch MED17.1.6',     'Bosch', 1),
('Bosch MED17.1.10',    'Bosch', 1),
('Bosch MED17.3',       'Bosch', 1),
('Bosch MED17.3.2',     'Bosch', 1),
('Bosch MED17.3.4',     'Bosch', 1),
('Bosch MED17.5',       'Bosch', 1),
('Bosch MED17.5.21',    'Bosch', 1),
('Bosch MED17.5.25',    'Bosch', 1),
('Bosch MED17.7',       'Bosch', 1),
('Bosch MED17.7.2',     'Bosch', 1),
('Bosch EDC15C2',       'Bosch', 1),
('Bosch EDC15C4',       'Bosch', 1),
('Bosch EDC15C5',       'Bosch', 1),
('Bosch EDC15C7',       'Bosch', 1),
('Bosch EDC15M',        'Bosch', 1),
('Bosch EDC15P+',       'Bosch', 1),
('Bosch EDC15VM+',      'Bosch', 1),
('Bosch EDC16C2',       'Bosch', 1),
('Bosch EDC16C3',       'Bosch', 1),
('Bosch EDC16C31',      'Bosch', 1),
('Bosch EDC16C34',      'Bosch', 1),
('Bosch EDC16C35',      'Bosch', 1),
('Bosch EDC16C36',      'Bosch', 1),
('Bosch EDC16C39',      'Bosch', 1),
('Bosch EDC16CP31',     'Bosch', 1),
('Bosch EDC16CP34',     'Bosch', 1),
('Bosch EDC16U1',       'Bosch', 1),
('Bosch EDC16U31',      'Bosch', 1),
('Bosch EDC16U34',      'Bosch', 1),
('Bosch EDC17C05',      'Bosch', 1),
('Bosch EDC17C06',      'Bosch', 1),
('Bosch EDC17C08',      'Bosch', 1),
('Bosch EDC17C10',      'Bosch', 1),
('Bosch EDC17C11',      'Bosch', 1),
('Bosch EDC17C42',      'Bosch', 1),
('Bosch EDC17C43',      'Bosch', 1),
('Bosch EDC17C44',      'Bosch', 1),
('Bosch EDC17C46',      'Bosch', 1),
('Bosch EDC17C50',      'Bosch', 1),
('Bosch EDC17C54',      'Bosch', 1),
('Bosch EDC17C55',      'Bosch', 1),
('Bosch EDC17C64',      'Bosch', 1),
('Bosch EDC17C74',      'Bosch', 1),
('Bosch EDC17C76',      'Bosch', 1),
('Bosch EDC17CP02',     'Bosch', 1),
('Bosch EDC17CP04',     'Bosch', 1),
('Bosch EDC17CP14',     'Bosch', 1),
('Bosch EDC17CP20',     'Bosch', 1),
('Bosch EDC17CP44',     'Bosch', 1),
('Bosch EDC17CP45',     'Bosch', 1),
('Bosch EDC17CP46',     'Bosch', 1),
('Bosch EDC17U01',      'Bosch', 1),
('Bosch EDC17U05',      'Bosch', 1),
('Bosch MEVD17.2',      'Bosch', 1),
('Bosch MEVD17.2.2',    'Bosch', 1),
('Bosch MEVD17.2.3',    'Bosch', 1),
('Bosch MEVD17.2.4',    'Bosch', 1),
('Bosch MEVD17.2.5',    'Bosch', 1),
('Bosch MEVD17.2.G',    'Bosch', 1),
('Bosch MEVD17.2.H',    'Bosch', 1),
('Bosch MG1CS001',      'Bosch', 1),
('Bosch MG1CS003',      'Bosch', 1),
('Bosch MG1CS011',      'Bosch', 1),
('Bosch MG1CS111',      'Bosch', 1),

-- Siemens / Continental / VDO
('Siemens SID201',      'Siemens', 1),
('Siemens SID202',      'Siemens', 1),
('Siemens SID203',      'Siemens', 1),
('Siemens SID204',      'Siemens', 1),
('Siemens SID206',      'Siemens', 1),
('Siemens SID208',      'Siemens', 1),
('Siemens SID209',      'Siemens', 1),
('Siemens SID301',      'Siemens', 1),
('Siemens SID302',      'Siemens', 1),
('Siemens SID305',      'Siemens', 1),
('Siemens SIM271',      'Siemens', 1),
('Siemens SIM272',      'Siemens', 1),
('Siemens SIM90',       'Siemens', 1),
('Continental EMS3120', 'Continental', 1),
('Continental EMS3125', 'Continental', 1),
('Continental EMS3132', 'Continental', 1),
('Continental EMS3150', 'Continental', 1),
('Continental EMS3155', 'Continental', 1),
('Continental EMS3180', 'Continental', 1),
('Continental EMS3185', 'Continental', 1),
('Continental PCR2.1',  'Continental', 1),
('Continental PCR7.1',  'Continental', 1),
('Continental SIMOS8.1','Continental', 1),
('Continental SIMOS8.4','Continental', 1),
('Continental SIMOS8.5','Continental', 1),
('Continental SIMOS10', 'Continental', 1),
('Continental SIMOS12', 'Continental', 1),
('Continental SIMOS18', 'Continental', 1),
('Continental SIMOS18.1','Continental',1),
('Continental SIMOS18.6','Continental',1),
('Continental SIMOS18.10','Continental',1),

-- Delphi / Delco
('Delphi DCM3.1',       'Delphi', 1),
('Delphi DCM3.2',       'Delphi', 1),
('Delphi DCM3.5',       'Delphi', 1),
('Delphi DCM3.7',       'Delphi', 1),
('Delphi DCM6.2',       'Delphi', 1),
('Delphi MT05',         'Delphi', 1),
('Delphi MT22',         'Delphi', 1),
('Delphi MT35E',        'Delphi', 1),
('Delphi MT80',         'Delphi', 1),
('Delphi MT86',         'Delphi', 1),
('Delphi MT92',         'Delphi', 1),

-- Denso
('Denso 275700-xxxx',   'Denso', 1),
('Denso 896xxx',        'Denso', 1),
('Denso SH7055',        'Denso', 1),
('Denso SH7058',        'Denso', 1),
('Denso SH72531',       'Denso', 1),
('Denso SH725xx',       'Denso', 1),

-- Magneti Marelli
('Magneti Marelli 4AM', 'Magneti Marelli', 1),
('Magneti Marelli 4HV', 'Magneti Marelli', 1),
('Magneti Marelli 4LV', 'Magneti Marelli', 1),
('Magneti Marelli 4MV', 'Magneti Marelli', 1),
('Magneti Marelli 5NF', 'Magneti Marelli', 1),
('Magneti Marelli 6F3', 'Magneti Marelli', 1),
('Magneti Marelli 6LP', 'Magneti Marelli', 1),
('Magneti Marelli 7GF', 'Magneti Marelli', 1),
('Magneti Marelli 8F2', 'Magneti Marelli', 1),
('Magneti Marelli 8F3', 'Magneti Marelli', 1),
('Magneti Marelli IAW4','Magneti Marelli', 1),
('Magneti Marelli IAW5','Magneti Marelli', 1),
('Magneti Marelli IAW7','Magneti Marelli', 1),

-- Valeo
('Valeo VD46',          'Valeo', 1),
('Valeo VD56',          'Valeo', 1),
('Valeo VD58',          'Valeo', 1),
('Valeo VD64',          'Valeo', 1),
('Valeo V40',           'Valeo', 1),
('Valeo V46',           'Valeo', 1),

-- Marelli / Motorola
('Motorola MPC5xx',     'Motorola', 1),

-- Sagem
('Sagem 3000',          'Sagem', 1),
('Sagem SID101',        'Sagem', 1),
('Sagem SID201',        'Sagem', 1),
('Sagem SID301',        'Sagem', 1),

-- Pierburg
('Pierburg EGS52',      'Pierburg', 1),

-- Hella
('Hella HAG2',          'Hella', 1);

-- ----------------------------------------
-- OKUMA YÖNTEMLERİ
-- ----------------------------------------
INSERT IGNORE INTO `reading_methods` (`name`, `is_active`) VALUES
('OBD (On-Board Diagnostics)', 1),
('BDM (Background Debug Mode)', 1),
('JTAG',                        1),
('Bootloader',                  1),
('Bench Mode',                  1),
('Tricore / Bootmode',          1),
('EEPROM Chip',                 1),
('Chip Okuma',                  1),
('Soket Adaptör',               1),
('Flash Okuma',                 1),
('K-Line',                      1),
('CAN Bus',                     1);
