CREATE TABLE IF NOT EXISTS `requests` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT UNSIGNED NOT NULL,
    `ticket_no` VARCHAR(20) NOT NULL,
    `brand_id` INT UNSIGNED DEFAULT NULL,
    `model_id` INT UNSIGNED DEFAULT NULL,
    `generation_id` INT UNSIGNED DEFAULT NULL,
    `engine_id` INT UNSIGNED DEFAULT NULL,
    `ecu_id` INT UNSIGNED DEFAULT NULL,
    `year` SMALLINT UNSIGNED DEFAULT NULL,
    `ecu_sw` VARCHAR(100) DEFAULT NULL,
    `ecu_hw` VARCHAR(100) DEFAULT NULL,
    `reading_method_id` INT UNSIGNED DEFAULT NULL,
    `plate_number` VARCHAR(20) DEFAULT NULL,
    `customer_note` TEXT DEFAULT NULL,
    `status` ENUM('pending','reviewing','processing','revision','completed','cancelled') NOT NULL DEFAULT 'pending',
    `total_credits` INT NOT NULL DEFAULT 0,
    `assigned_admin_id` INT UNSIGNED DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_requests_ticket` (`ticket_no`),
    INDEX `idx_requests_user` (`user_id`),
    INDEX `idx_requests_status` (`status`),
    INDEX `idx_requests_created` (`created_at`),
    CONSTRAINT `fk_requests_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_requests_brand` FOREIGN KEY (`brand_id`) REFERENCES `brands`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_requests_model` FOREIGN KEY (`model_id`) REFERENCES `vehicle_models`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_requests_generation` FOREIGN KEY (`generation_id`) REFERENCES `generations`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_requests_engine` FOREIGN KEY (`engine_id`) REFERENCES `engines`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_requests_ecu` FOREIGN KEY (`ecu_id`) REFERENCES `ecus`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_requests_reading_method` FOREIGN KEY (`reading_method_id`) REFERENCES `reading_methods`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_requests_admin` FOREIGN KEY (`assigned_admin_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
